CREATE TABLE EMPLOYEE
(ID VARCHAR(10) NOT NULL,
startdate DATE,
Jobtype VARCHAR(15),
First VARCHAR(15) NOT NULL,
Minit CHAR,
Last VARCHAR(15) NOT NULL,
Street VARCHAR(20),
City VARCHAR(15),
State VARCHAR(15),
Zip INT,
HourlyrateID VARCHAR(10),
SupervisorID VARCHAR(10),
ConcessionRevenueID VARCHAR(10),
ZooAdmissionRevenueID VARCHAR(10),
PRIMARY KEY (ID),
CONSTRAINT sup_id FOREIGN KEY (SupervisorID) REFERENCES EMPLOYEE(ID)
) ;



CREATE TABLE HourlyRate
(ID VARCHAR(10) NOT NULL,
HourlyRate INT NOT NULL,
PRIMARY KEY (ID)
) ;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT emp_HR_ID FOREIGN KEY (HourlyrateID) REFERENCES HourlyRate(ID) 
ON DELETE CASCADE;

CREATE TABLE SPECIES
(ID VARCHAR(10) NOT NULL,
Name VARCHAR(15) NOT NULL,
Foodcost INT NOT NULL,
PRIMARY KEY (ID)
) ;


CREATE TABLE ENCLOSURE
(ID VARCHAR(10) NOT NULL,
BuildingID VARCHAR(10),
SqFt INT NOT NULL,
PRIMARY KEY (ID, BuildingID)
) ;

CREATE TABLE ANIMAL
(ID VARCHAR(10) NOT NULL,
BuildingID VARCHAR(10),
SpeciesID VARCHAR(10),
Status VARCHAR(15),
BirthYear DATE,
EnclosureID VARCHAR(10),
PRIMARY KEY (ID),
CONSTRAINT sp_id FOREIGN KEY (SpeciesID) REFERENCES SPECIES(ID),
CONSTRAINT bld_id FOREIGN KEY (BuildingID) REFERENCES ENCLOSURE(BuildingID),
CONSTRAINT en_id FOREIGN KEY (EnclosureID) REFERENCES ENCLOSURE(ID)
) ;



CREATE TABLE BUILDING
(ID VARCHAR(10) NOT NULL,
Name VARCHAR(10),
Type VARCHAR(10),
PRIMARY KEY (ID)
) ;

ALTER TABLE ENCLOSURE
ADD CONSTRAINT  enc_bld_ID FOREIGN KEY (BuildingID) REFERENCES BUILDING(ID) 
ON DELETE CASCADE;

CREATE TABLE Revenue_Types
(ID VARCHAR(10) NOT NULL,
Name VARCHAR(10),
Type VARCHAR(10),
BuildingID VARCHAR(10),
PRIMARY KEY (ID),
CONSTRAINT  bldn_ID FOREIGN KEY (BuildingID) REFERENCES BUILDING(ID) 
) ;


CREATE TABLE Revenue_Events
(DateTime DATE NOT NULL,
RevenueID VARCHAR(10) NOT NULL,
TicketsSold INT,
Revenue INT,
PRIMARY KEY (DateTime, RevenueID),
CONSTRAINT  rvn_ID FOREIGN KEY (RevenueID) REFERENCES Revenue_Types(ID) 
) ;

CREATE TABLE Animal_Show
(RevenueID VARCHAR(10) NOT NULL,
SeniorPrice INT,
AdultPrice INT,
ChildPrice INT,
#perday VARCHAR(10),
PRIMARY KEY (RevenueID),
CONSTRAINT  as_rvn_ID FOREIGN KEY (RevenueID) REFERENCES Revenue_Types(ID) 
) ;



CREATE TABLE CONCESSION
(RevenueID VARCHAR(10) NOT NULL,
product VARCHAR(10),
PRIMARY KEY (RevenueID),
CONSTRAINT  Crvn_ID FOREIGN KEY (RevenueID) REFERENCES Revenue_Types(ID) 
) ;

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT cncs_ID FOREIGN KEY (ConcessionRevenueID) REFERENCES CONCESSION(RevenueID) 
ON DELETE CASCADE;



CREATE TABLE Zoo_Admission
(RevenueID VARCHAR(10) NOT NULL,
SeniorPrice INT,
AdultPrice INT,
ChildPrice INT,
PRIMARY KEY (RevenueID),
CONSTRAINT  Za_rvn_ID FOREIGN KEY (RevenueID) REFERENCES Revenue_Types(ID) 
) ;

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT zar_ID FOREIGN KEY (ZooAdmissionRevenueID) REFERENCES Zoo_Admission(RevenueID) 
ON DELETE CASCADE;


CREATE TABLE Participates_In
(SpeciesID VARCHAR(10) NOT NULL,
AnimalShowRevenueID VARCHAR(10) NOT NULL,
#req’d VARCHAR(10),
PRIMARY KEY (SpeciesID, AnimalShowRevenueID),
CONSTRAINT  sps_ID FOREIGN KEY (SpeciesID) REFERENCES SPECIES(ID),
CONSTRAINT  ASrev_ID FOREIGN KEY (AnimalShowRevenueID) REFERENCES Animal_Show(RevenueID)
) ;

CREATE TABLE Cares_For
(SpeciesID VARCHAR(10) NOT NULL,
EmployeeID VARCHAR(10) NOT NULL,
PRIMARY KEY (SpeciesID, EmployeeID ),
CONSTRAINT spcs_id FOREIGN KEY (SpeciesID) REFERENCES SPECIES(ID),
CONSTRAINT emp_id FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(ID)
) ;